language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
# install dependencies
install: 
    - pip install -r requirements/development.txt
# style guide test, temp ignore of some django generated code
before_script:
    - flake8 --exclude=migrations,settings,manage.py,.venv,docs,invoicing .
# run main tests
script:
    - coverage run --source=core,api manage.py test
# report code coverage to coveralls
after_success:
    - coveralls
